#ifndef _COMMON_DEFS_INCLUDE
#define _COMMON_DEFS_INCLUDE


#define WINDOWS_WIDTH 960
#define WINDOWS_HEIGHT 480
#define WINDOWS_LEFT_SCROLLING_MARGIN 30
#define WINDOWS_RIGHT_SCROLLING_MARGIN 930
#define WINDOWS_TOP_SCROLLING_MARGIN 30
#define WINDOWS_BOTTOM_SCROLLING_MARGIN 450
#define WINDOWS_POSITION_HOR 100
#define WINDOWS_POSITION_VER 100
#define NON_BLOCKING_PIXEL 0
#define MAP_BLOCKING_PIXEL 255
#define LEM_BLOCKING_PIXEL 190



enum PixelFormat { TEXTURE_PIXEL_FORMAT_RGB, TEXTURE_PIXEL_FORMAT_RGBA, TEXTURE_PIXEL_FORMAT_L };




#endif //_COMMON_DEFS_INCLUDE


